/* Lógico_1: */

CREATE TABLE USUARIO (
    ID INTEGER PRIMARY KEY,
    nome CHARACTER,
    senha CHARACTER,
    nivel_usuario INTEGER
);

CREATE TABLE MUNICAO (
    ID INTEGER PRIMARY KEY,
    nome CHARACTER,
    id_marca INTEGER,
    calibre DECIMAL,
    peso DECIMAL,
    quantidade INTEGER,
    FK_MARCA_ID INTEGER
);

CREATE TABLE POLICIAL (
    ID INTEGER PRIMARY KEY,
    nome CHARACTER,
    cpf CHARACTER,
    rg CHARACTER,
    qra CHARACTER,
    data_nascimento CHARACTER,
    telefone CHARACTER,
    matricula CHARACTER,
    senha CHARACTER
);

CREATE TABLE FORNECEDOR (
    ID INTEGER PRIMARY KEY,
    razao_social CHARACTER,
    cnpj CHARACTER,
    inscricao CHARACTER
);

CREATE TABLE ENTRADA_ESTOQUE (
    ID INTEGER PRIMARY KEY,
    id_fornecedor INTEGER,
    id_municao INTEGER,
    data TIMESTAMP,
    quantidade INTEGER,
    FK_MUNICAO_ID INTEGER
);

CREATE TABLE SAIDA_ESTOQUE (
    ID INTEGER PRIMARY KEY,
    data TIMESTAMP,
    id_municao INTEGER,
    quantidade INTEGER,
    descicao CHARACTER,
    FK_MUNICAO_ID INTEGER
);

CREATE TABLE MARCA (
    ID INTEGER PRIMARY KEY,
    nome CHARACTER
);

CREATE TABLE LANCAMENTO (
    FK_MUNICAO_ID INTEGER,
    FK_POLICIAL_ID INTEGER,
    ID INTEGER PRIMARY KEY,
    tipo_lancamento INTEGER,
    data TIMESTAMP,
    id_usuario INTEGER
);

CREATE TABLE FORNECEDOR_MUNICAO (
    FK_FORNECEDOR_ID INTEGER,
    FK_MUNICAO_ID INTEGER
);
 
ALTER TABLE MUNICAO ADD CONSTRAINT FK_MUNICAO_2
    FOREIGN KEY (FK_MARCA_ID)
    REFERENCES MARCA (ID)
    ON DELETE CASCADE;
 
ALTER TABLE ENTRADA_ESTOQUE ADD CONSTRAINT FK_ENTRADA_ESTOQUE_2
    FOREIGN KEY (FK_MUNICAO_ID)
    REFERENCES MUNICAO (ID)
    ON DELETE CASCADE;
 
ALTER TABLE SAIDA_ESTOQUE ADD CONSTRAINT FK_SAIDA_ESTOQUE_2
    FOREIGN KEY (FK_MUNICAO_ID)
    REFERENCES MUNICAO (ID)
    ON DELETE CASCADE;
 
ALTER TABLE LANCAMENTO ADD CONSTRAINT FK_LANCAMENTO_2
    FOREIGN KEY (FK_MUNICAO_ID)
    REFERENCES MUNICAO (ID)
    ON DELETE SET NULL;
 
ALTER TABLE LANCAMENTO ADD CONSTRAINT FK_LANCAMENTO_3
    FOREIGN KEY (FK_POLICIAL_ID)
    REFERENCES POLICIAL (ID)
    ON DELETE SET NULL;
 
ALTER TABLE FORNECEDOR_MUNICAO ADD CONSTRAINT FK_FORNECEDOR_MUNICAO_1
    FOREIGN KEY (FK_FORNECEDOR_ID)
    REFERENCES FORNECEDOR (ID)
    ON DELETE SET NULL;
 
ALTER TABLE FORNECEDOR_MUNICAO ADD CONSTRAINT FK_FORNECEDOR_MUNICAO_2
    FOREIGN KEY (FK_MUNICAO_ID)
    REFERENCES MUNICAO (ID)
    ON DELETE SET NULL;